config/routes.rb
Rails.application.routes.draw do
  resources :properties

  resources :testfiles

  resources :users

  resources :materials

end

app/models/testfile.rb
class Testfile < ActiveRecord::Base
end

app/controllers/testfiles_controller.rb
class TestfilesController < ApplicationController
  before_action :set_testfile, only: [:show, :edit, :update, :destroy]

  # GET /testfiles
  # GET /testfiles.json
  def index
    @testfiles = Testfile.all
  end

  # GET /testfiles/1
  # GET /testfiles/1.json
  def show
  end

  # GET /testfiles/new
  def new
    @testfile = Testfile.new
  end

  # GET /testfiles/1/edit
  def edit
  end

  # POST /testfiles
  # POST /testfiles.json
  def create
    @testfile = Testfile.new(testfile_params)

    respond_to do |format|
      if @testfile.save
        format.html { redirect_to @testfile, notice: 'Testfile was successfully created.' }
        format.json { render :show, status: :created, location: @testfile }
      else
        format.html { render :new }
        format.json { render json: @testfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testfiles/1
  # PATCH/PUT /testfiles/1.json
  def update
    respond_to do |format|
      if @testfile.update(testfile_params)
        format.html { redirect_to @testfile, notice: 'Testfile was successfully updated.' }
        format.json { render :show, status: :ok, location: @testfile }
      else
        format.html { render :edit }
        format.json { render json: @testfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testfiles/1
  # DELETE /testfiles/1.json
  def destroy
    @testfile.destroy
    respond_to do |format|
      format.html { redirect_to testfiles_url, notice: 'Testfile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testfile
      @testfile = Testfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testfile_params
      params.require(:testfile).permit(:filename, :content_type, :file_contents, :confidence_rank)
    end
end

app/helpers/testfiles_helper.rb
module TestfilesHelper
end

app/views/testfiles/_form.html.erb
<%= form_for(@testfile) do |f| %>
  <% if @testfile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testfile.errors.count, "error") %> prohibited this testfile from being saved:</h2>

      <ul>
      <% @testfile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filename %><br>
    <%= f.text_field :filename %>
  </div>
  <div class="field">
    <%= f.label :content_type %><br>
    <%= f.text_field :content_type %>
  </div>
  <div class="field">
    <%= f.label :file_contents %><br>
    <%= f.text_field :file_contents %>
  </div>
  <div class="field">
    <%= f.label :confidence_rank %><br>
    <%= f.number_field :confidence_rank %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testfiles/edit.html.erb
<h1>Editing Testfile</h1>

<%= render 'form' %>

<%= link_to 'Show', @testfile %> |
<%= link_to 'Back', testfiles_path %>

app/views/testfiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Testfiles</h1>

<table>
  <thead>
    <tr>
      <th>Filename</th>
      <th>Content type</th>
      <th>File contents</th>
      <th>Confidence rank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testfiles.each do |testfile| %>
      <tr>
        <td><%= testfile.filename %></td>
        <td><%= testfile.content_type %></td>
        <td><%= testfile.file_contents %></td>
        <td><%= testfile.confidence_rank %></td>
        <td><%= link_to 'Show', testfile %></td>
        <td><%= link_to 'Edit', edit_testfile_path(testfile) %></td>
        <td><%= link_to 'Destroy', testfile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Testfile', new_testfile_path %>

app/views/testfiles/new.html.erb
<h1>New Testfile</h1>

<%= render 'form' %>

<%= link_to 'Back', testfiles_path %>

app/views/testfiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @testfile.filename %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @testfile.content_type %>
</p>

<p>
  <strong>File contents:</strong>
  <%= @testfile.file_contents %>
</p>

<p>
  <strong>Confidence rank:</strong>
  <%= @testfile.confidence_rank %>
</p>

<%= link_to 'Edit', edit_testfile_path(@testfile) %> |
<%= link_to 'Back', testfiles_path %>